fix: job for setting short_env

diff --git a/.github/workflows/deploy_lambda.yml b/.github/workflows/deploy_lambda.yml
--- a/.github/workflows/deploy_lambda.yml
+++ b/.github/workflows/deploy_lambda.yml
@@ -46,9 +46,22 @@ jobs:
       terraform_changed: ${{ steps.terraform_changed.outputs.changed }}
       code_changed: ${{ steps.code_changed.outputs.changed }}
 
+  short_env:
+    name: 'Define Short Env'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set Short Env
+        run: |
+          case ${{ inputs.environment }} in
+            development) echo "::set-output name=short_env::dev" ;;
+            release) echo "::set-output name=short_env::release" ;;
+            production) echo "::set-output name=short_env::prod" ;;
+            *) echo "Invalid environment" && exit 1 ;;
+          esac
+
   terraform:
     name: Terraform
-    needs: [changes]
+    needs: [changes, short_env]
     if: ${{ needs.changes.outputs.terraform_changed == 'true'}}
     runs-on: ubuntu-latest
     env:
@@ -91,20 +104,12 @@ jobs:
           chmod 600 "$SSH_PATH/id_rsa"
           eval $(ssh-agent)
           ssh-add "$SSH_PATH/id_rsa"
-      - name: Set Short Env
-        run: |
-          case ${{ inputs.environment }} in
-            development) echo "short_env=dev" >> $GITHUB_ENV ;;
-            release) echo "short_env=release" >> $GITHUB_ENV ;;
-            production) echo "short_env=prod" >> $GITHUB_ENV ;;
-            *) echo "Invalid environment" && exit 1 ;;
-          esac
       - run: lerna bootstrap
       - name: Get packages environment variables
-        run: lerna run pull-env:${{ env.short_env }}
+        run: lerna run pull-env:${{ needs.short_env.outputs.short_env }}
         continue-on-error: true
       - name: Get shared environment variables
-        run: yarn pull-shared-env:${{ env.short_env }}
+        run: yarn pull-shared-env:${{ needs.short_env.outputs.short_env }}
         continue-on-error: true
       - run: terraform init
       - run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
@@ -112,7 +117,7 @@ jobs:
 
   functions:
     name: 'Functions'
-    needs: [changes, terraform]
+    needs: [changes, terraform, short_env]
     if: ${{ needs.changes.outputs.code_changed == 'true' }}
     timeout-minutes: 5
     runs-on: ubuntu-latest
@@ -159,4 +164,4 @@ jobs:
       - name: Build modified packages
         run: lerna run build --since origin/${{ github.ref_name }}~1 --exclude-dependents
       - name: Deploy modified packages
-        run: lerna run deploy:${{ env.short_env }} --since origin/${{ github.ref_name }}~1 --exclude-dependents
+        run: lerna run deploy:${{ needs.short_env.outputs.short_env }} --since origin/${{ github.ref_name }}~1 --exclude-dependents
diff --git a/.github/workflows/deploy_ui.yml b/.github/workflows/deploy_ui.yml
--- a/.github/workflows/deploy_ui.yml
+++ b/.github/workflows/deploy_ui.yml
@@ -34,11 +34,18 @@ jobs:
     name: Build and Deploy
     runs-on: ubuntu-latest
     steps:
+      - name: Set s3 bucket on env
+        run: |
+          case ${{ inputs.environment }} in
+            development) echo "s3_full_path=dev.gbrkr.com/${{ inputs.portal }}/${{ inputs.cf_path }}" >> $GITHUB_ENV ;;
+            release) echo "s3_full_path=dev.gbrkr.com/${{ inputs.portal }}/${{ inputs.cf_path }}" >> $GITHUB_ENV ;;
+            production) echo "s3_full_path=gb-ui-v2/${{ inputs.portal }}/${{ inputs.cf_path }}" >> $GITHUB_ENV ;;
+            *) echo "Invalid environment" && exit 1 ;;
+          esac
       - name: Checkout
         uses: actions/checkout@v2
         with:
           ref: ${{ github.ref_name }}
-
       - name: Generate and publish release
         uses: release-drafter/release-drafter@v5
         if: inputs.environment == 'production'
@@ -46,31 +53,25 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           publish: true
-
       - uses: actions/setup-node@v1
         with:
           node-version: 14
-
       - name: Install Dependencies
         run: npm ci --no-optional
-
       - name: Configure AWS Tools Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
-
       - name: Pull environment variables
         run: |
           npm run pull-env:ci
           cat .env.${{ inputs.environment }} > .env.production
         env: 
           GROUNDBREAKER_ENVIRONMENT: ${{ inputs.environment }}
-
       - name: Build App
         run: npm run build
-
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -80,27 +81,15 @@ jobs:
           role-to-assume: ${{ secrets.AWS_ROLE }}
           role-duration-seconds: 1200
           role-session-name: ${{ inputs.environment }}
-
-      - name: Set s3 bucket on env
-        run: |
-          case ${{ inputs.environment }} in
-            development) echo "s3_full_path=dev.gbrkr.com/${{ inputs.portal }}/${{ inputs.cf_path }}" >> $GITHUB_ENV ;;
-            release) echo "s3_full_path=dev.gbrkr.com/${{ inputs.portal }}/${{ inputs.cf_path }}" >> $GITHUB_ENV ;;
-            production) echo "s3_full_path=gb-ui-v2/${{ inputs.portal }}/${{ inputs.cf_path }}" >> $GITHUB_ENV ;;
-            *) echo "Invalid environment" && exit 1 ;;
-          esac
-
       - name: Deploy
         run: |
           aws s3 rm --recursive s3://${{ env.s3_full_path }}
           aws s3 sync dist s3://${{ env.s3_full_path }}
-
       - name: Add index cache invalidation metadata
         run: |
           aws s3 cp s3://${{ env.s3_full_path }}/index.html s3://${{ env.s3_full_path }}/index.html \
             --metadata-directive REPLACE \
             --cache-control max-age=0 \
             --content-type "text/html"
-
       - name: Invalidate cache
         run: aws cloudfront create-invalidation --distribution-id ${{ inputs.distribution_id }} --paths "/${{ inputs.cf_path }}/*"
